[package]
name = "algorithm"
version = "0.1.0"
authors = ["Guo-lab <1811400940@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.0"
